export const TERMS_REQUEST = 'TERMS_REQUEST';
export const TERMS_ACTIVE = 'TERMS_ACTIVE';
export const TERM_REQUEST = 'TERM_REQUEST';
export const TERM_ACTIVE = 'TERM_ACTIVE';
export const SPLIT_REQUEST =  {VERTICAL: 'VERTICLAL', HORIZONTAL: 'HORIZONTAL'};
